### ISSUE TITLE
viewflow cause memory leak?

### ISSUE THREAD

**Issue by gaoneng102** [pakerfeldt/android-viewflow#110]
I detect app memory leak by LeakCanary while app is working with android-viewflow
![screenshot_20160122-102942](https://cloud.githubusercontent.com/assets/7017463/12501005/745337e2-c0f3-11e5-9495-6d125af93d01.png)

**Comment by pakerfeldt** [comment]
If anyone wants to solve this leak I'm happy to merge a PR.

**Comment by gaoneng102** [comment]
@pakerfeldt I'm so sorry,it's not android-viewflow cause memory leak.My colleague put a handler for calculagraph in viewflow then the handler cause memory leak.sorry again!

**Comment by pakerfeldt** [comment]
Thanks
