### ISSUE TITLE
java.lang.OutOfMemoryError: bitmap size exceeds VM budget

### ISSUE THREAD

**Issue by delneet** [pakerfeldt/android-viewflow#12]
I get the following error when specifying 20x 231kb png's with transparency
I already set the buffer to 1

07-01 15:44:02.096: ERROR/AndroidRuntime(31557): java.lang.OutOfMemoryError: bitmap size exceeds VM budget

Any Ideas?

I've also tried not specifying the R.drawable.pic1 in the int array but finding them through getIdentifier and getDrawable, but to no luck...

**Comment by pakerfeldt** [comment]
You might want to run DDMS to check heap usage. 
If you have a buffer of 1 then at most three views should be loaded at a time. So, what happens if you decrease the number of png's to 3 instead of 20. Still causing the OutOfMemoryError? If not, it seems like a bug in the viewflow library.

**Comment by delneet** [comment]
Thanks for your quick reply!

I have a heap size of 2.7MB (with 3 pics)
This doesn't change when I increase the num of pics to lets say 10.

When I decrease the card_count in my ImageAdapter from 20 to 3 (so that getCount() returns 3) everything is just fine.
But anything higher than 3 causes the error.
Also when I set it to 3 and then start another activity with an image, my app crashes with this error.
It seems like the resources are all loaded and stay in memory?

does this help?
http://www.helloandroid.com/tutorials/how-avoid-outofmemory-error-oom-ugly-truth-revealed

**Comment by delneet** [comment]
It seems the issue lies in the rest of the application consuming too much bitmap vm
decreasing other images (like background on ImageItemView) results in no more errors.
Sorry, seems to be false alarm

**Comment by pakerfeldt** [comment]
No worries!
