### ISSUE TITLE
request: pinch/zoom images

### ISSUE THREAD

**Issue by delneet** [pakerfeldt/android-viewflow#13]
I'd like to pinch/zoom the current image (or the whole current image container layout).
Where would you recommend adjusting viewflow?

**Comment by pakerfeldt** [comment]
Perhaps you might find this an interesting read: http://android-developers.blogspot.com/2010/06/making-sense-of-multitouch.html
I don't believe that the viewflow library in any particular way, instead you should add a View to the viewflow which supports what you're asking for.

**Comment by delneet** [comment]
I know the article.
Was just wondering if you were planning on implementing this.
I will try and put it in my ImageView myself.

Thank you!

**Comment by pakerfeldt** [comment]
I'm afraid that's not planned. The right thing to do would be to implement this in the View itself I believe.
