### ISSUE TITLE
Jarify

### ISSUE THREAD

**Issue by Miserlou** [pakerfeldt/android-viewflow#15]
This project needs a .jar that I can add to my workspace without having to import the whole project into eclipse!

**Comment by pakerfeldt** [comment]
I may very well add a jar file for people to download but I cannot guarantee that it's always up to date. Creating a new jar file for every commit adds quite some overhead. Would that be acceptable?

**Comment by Miserlou** [comment]
That's fine - but does git overhead really matter that much? It's not like GitHub has any space limits, and git checkout is pretty damn fast anyway. _shrug_ Either way is fine though - I'd just commit the Jar though, because otherwise I'd end up having to keep the Jar on the download page up to date because I'm OCD like that.

**Comment by pakerfeldt** [comment]
I didn't mean overhead as in space but as in time (exporting jar file from eclipse, uploading to github).

**Comment by Miserlou** [comment]
Ah, I see. In that case just write the ant script and add instructions to 'ant jar' in the README, maybe?

**Comment by pakerfeldt** [comment]
Try it out!

**Comment by Miserlou** [comment]
Cool thanks!
