### ISSUE TITLE
MinSDK version is not correct

### ISSUE THREAD

**Issue by rp-** [pakerfeldt/android-viewflow#16]
Hi!

I tried to get it work with android 1.6(API4) but there are 2 issues with that.
- ViewFlow.java:626 View.Group.LayoutParams.MATCH_PARENT
  In API4 there is no MATCH_PARENT, it should be named FILL_PARENT
- ViewFlow.java:131 protected void onConfigurationChanged(Configuration newConfig) {
  API4 doesn't have an onConfigurationChanged() method in AdapterView class.

I got it working by commenting out the onConfigurationChanged method, but I don't know what this will cause.

Would be cool if this library could maintain API4 compatibility for a little longer.

**Comment by pakerfeldt** [comment]
Thanks for pointing this out! The onConfigurationChanged method is needed for proper handling of orientation changes. As now mentioned in the README, you need to forward this call from your Activity yourself if you plan on supporting an API level < 8. Please see Caveats in README and CircleViewFlowExample for more detail.

**Comment by rp-** [comment]
Thank you for supporting API4.

Just had a problem with your changes with your copyright comment, the XML resource parser had problems with the '--' token within the document. If you remove the second comment opening tag '<!--' it works

**Comment by pakerfeldt** [comment]
Hmm, I don't quite get that error. Which file are you talking about, attrs.xml? Can't see any second comment opening.

**Comment by rp-** [comment]
viewflow/res/values/attrs.xml
line 3

**Comment by pakerfeldt** [comment]
Oh, my mistake. I hadn't commited everything. Pushing it to the repository as we speak.
