### ISSUE TITLE
Problem with MeasureSpec.EXACTLY

### ISSUE THREAD

**Issue by nadam** [pakerfeldt/android-viewflow#20]
I'm trying to replace a Gallery widget with ViewFlow and I get an error that "ViewFlow can only be used in EXACTLY mode." I assume that the cause of this is that I have the ViewFlow inside a ScrollView.

Is this "EXACTLY-requirement" necessary or can we make ViewFlow more similar to Gallery, for instance by extending AbsSpinner instead of AdapterView<Adapter>?

**Comment by pakerfeldt** [comment]
That piece of code is a remnant from the RealViewSwitcher which viewflow is based on. Not sure whether it's required or not but I suppose it's not. From what I can see, it is not really recommended to extend AbsSpinner but we could very well re-write our onMeasure method with inspiration from the AbsSpinner.

**Comment by nadam** [comment]
Ok, I'll give it a try and let you know the result.

**Comment by nadam** [comment]
I ran into problems with the horizontal scrolling, so I decided to use the standard Gallery widget instead and made some minor changes to CircleFlowIndicator to have it work together with Gallery.
