### ISSUE TITLE
Dimension format for textSize attribute?

### ISSUE THREAD

**Issue by costimuraru** [pakerfeldt/android-viewflow#25]
Hello,

I've been using your library and noticed that the textSize attribute (defined in res/values/attrs.xml) is formatted as an integer. Wouldn't it be better to set its format to "dimension", so that we could use sp or other dimension values?

You could then change the code in TitleFlowIndicator.java to something like:
float textSize = a.getDimension(R.styleable.TitleFlowIndicator_textSize, TEXT_SIZE);

There are also other attributes whose format should be changed to "dimension" in order to support multiple screens and user preferences. That's just my opinion.

The second issue, imho, is not being able to directly click adjacent views' titles instead of doing a fling gesture.

I apologize in advance if I misread some information.
Good job with this library! Keep it up!

Costi

**Comment by pakerfeldt** [comment]
Good point with dimension. I believe I have corrected that issue now. As for the other feature request, please file a new separate issue. I will close this one now.
