### ISSUE TITLE
CircleFlowIndicator

### ISSUE THREAD

**Issue by cuiwenpeng** [pakerfeldt/android-viewflow#26]
help.....When using a handler to load the server data, CircleFlowIndicator not display correctly.
               private void loadPage(){
    list = aj.getAdvListHttp();

```
Message msg = new Message();
msg.what=0;
mh.sendMessage(msg);

          }

           public boolean handleMessage(Message msg) {

viewflow.setAdapter(new BigViewAdapter(this, list));
viewflow.setFlowIndicator(viewflowindic);
findViewById(R.id.adv_load).setVisibility(View.INVISIBLE);

adv_List.setVisibility(View.INVISIBLE);
adv_List.setAdapter(new ViewAdapter(this, list));
return false;
            }
```

CircleFlowIndicator Always shows three small dots.

**Comment by pakerfeldt** [comment]
Seems like you haven't told your circle flow indicator about your viewflow instance.
Make sure you call setViewFlow(...) with your viewflowindic.
