### ISSUE TITLE
TitleFlowIndicator footerLine calculation issue

### ISSUE THREAD

**Issue by sergk79** [pakerfeldt/android-viewflow#34]
Hi!

I found an issue in footerLine vert coordinate calculation (TitleFlowIndicator.java onDraw() function). 
The following code doesn't work properly if the line thickness is more than 1 pixel:
        path.moveTo(0, getHeight()-footerLineHeight);
        path.lineTo(getWidth(), getHeight()-footerLineHeight);

To fix this I suggest to do the following:
        int coordY = getHeight()-1;
        coordY -= (footerLineHeight%2 == 1) ? footerLineHeight/2 : footerLineHeight/2-1;
        path.moveTo(0, coordY);
        path.lineTo(getWidth(), coordY);

**Comment by pakerfeldt** [comment]
I can't see what the issue is about? Tried with several different line heights but it doesn't look weird to me.

**Comment by sergk79** [comment]
Yeah, it's hard to see it with transparent background. 
I found this issue when I added a background drawable for TitleFlowIndicator. Look at this screenshot:
http://lh3.googleusercontent.com/-29H9sAjZj0k/TkoddUHR3xI/AAAAAAAAAVU/bFoOkqPq9ZQ/s779/TitleFlowIndicator_footerLine_issue.png

**Comment by pakerfeldt** [comment]
Ah, perfect! I'll make sure your fix will get commited asap.
