### ISSUE TITLE
setSelection causing force closed

### ISSUE THREAD

**Issue by elnoxvie** [pakerfeldt/android-viewflow#36]
I have more than 10 views.. 
but if i were in the 1st view and do a set selection to the 10th view, it will cause a force closed. 

Putting an AppBuffer > 10 will help but i can't predict how many i might have since the view is loaded dynamically.

**Comment by pakerfeldt** [comment]
And what does the stack trace look like?

**Comment by elnoxvie** [comment]
Hi, 

Here is the stack trace: 

08-15 15:16:58.810: ERROR/AndroidRuntime(4659): java.lang.NullPointerException
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at com.handyapps.GTasks.Task.TaskView.load(TaskView.java:53)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at com.handyapps.GTasks.Task.TaskView.<init>(TaskView.java:40)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at com.handyapps.GTasks.Adapter.AndroidVersionAdapter.getView(AndroidVersionAdapter.java:97)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at org.taptwo.android.widget.ViewFlow.makeAndAddView(ViewFlow.java:647)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at org.taptwo.android.widget.ViewFlow.setSelection(ViewFlow.java:533)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at com.handyapps.GTasks.TaskList.TasklistView$3.onItemClick(TasklistView.java:145)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at android.widget.AdapterView.performItemClick(AdapterView.java:284)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at android.widget.ListView.performItemClick(ListView.java:3382)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at android.widget.AbsListView$PerformClick.run(AbsListView.java:1696)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at android.os.Handler.handleCallback(Handler.java:587)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at android.os.Handler.dispatchMessage(Handler.java:92)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at android.os.Looper.loop(Looper.java:123)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at android.app.ActivityThread.main(ActivityThread.java:4627)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at java.lang.reflect.Method.invokeNative(Native Method)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at java.lang.reflect.Method.invoke(Method.java:521)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
08-15 15:16:58.810: ERROR/AndroidRuntime(4659):     at dalvik.system.NativeStart.main(Native Method)

**Comment by pakerfeldt** [comment]
There seems to be a NullPointerException somewhere in your code when ViewFlow calls getView (in your adapter) for the particular view to show. I suggest you check TaskView at line 53 to see why the null pointer occurs.

**Comment by elnoxvie** [comment]
Thanks. It works now by commenting the following line but it seems much more sluggish now. 
if(convertView == null) {}

For some reason, it seems that if i do a set selection, the convertView doesn't get detected as null. 
Anyway, i will try to check again. 

Thanks for the help.

**Comment by pakerfeldt** [comment]
convertView does not have to be null. You might very well be given an old view that you're supposed to use instead of inflating a new one. For an example of getView() and how convertView is used, see: 
https://github.com/pakerfeldt/android-viewflow/blob/master/viewflow-example/src/org/taptwo/android/widget/viewflow/example/AndroidVersionAdapter.java
