### ISSUE TITLE
page frozen after setSelection() is called

### ISSUE THREAD

**Issue by Cliffus** [pakerfeldt/android-viewflow#48]
Hi

I'm using the Viewflow app for one of our customers. It all seems to work fine until I set the selected page with the setSelection() method in the ViewFlow class. The pages (child views of the ViewFlow view) seem to be frozen, Android stops drawing layout updates for them.

In my case, the pages contain list views. I can still scroll them but the layout updates are not drawn anymore. If you then switch to the next page and then go back, the page is redrawn (but is still frozen).

It sometimes also appears on first startup, any idea what could go wrong?

Thanks in advance!
Cliff

**Comment by elnoxvie** [comment]
I also noticed this on the latest update. I switched back to the old version for the time being.

**Comment by Cliffus** [comment]
thanks for the comment! what version are you using?

**Comment by pakerfeldt** [comment]
You have some sort of background service changing the layout of the list view? I'm trying to figure out how to re-produce this issue. Would it be possible for you to alter the "Different views" layout in viewflow-example and have it re-produce your problem?

**Comment by Cliffus** [comment]
Hi!

I just 'solved' the issue, there was a stupid bug in my adapter which caused views to not recycle anymore... _deeply ashamed_ ;-)

but still, this might be a bug in the viewflow class, this is what happens:

I initialize the adapter, set it on the viewflow class with selected index 0. On user interaction, I set the index to 1 (or something else), the views in the adapater are not recycled so they are recreated in the setSelected() method. On that moment, all views in the adapter are frozen.

I hope this scenario can help you find the cause of this issue, but it's not a big one ;-)

**Comment by pakerfeldt** [comment]
Yes, that's a known issue that setSelection causes every view in the buffer to be re-fetched from the adapter. Still they are "re-cycled" in the sense that old views are passed to the getView method in your adapter (hence you don't need to inflate the view). But you still have to populate the view with data, yes.

**Comment by Cliffus** [comment]
that wasn't really the problem, the views inside the viewflow view seemed like some kind of 'screenshots' of the views. The UI thread wasn't looping inside them anymore.

I could only reproduce the issue on Android 2.1+

**Comment by pakerfeldt** [comment]
So, is there still some kind of outstanding issue or did you resolve it in your adapter?

**Comment by Cliffus** [comment]
for me, there is no issue anymore. there is only an issue when the developer decides to not use view recyling.

I'll close this one ;-)

**Comment by pakerfeldt** [comment]
Cool!

**Comment by euvid** [comment]
I have the same problem, in which my listview updates only after one or several touches, such as there is no getView called on listview adapter. Can you explain me how did you resolve the problem. I know it's recommended to use viewPager, but i have used this for a while and i addapted the viewFlow for my needs
