### ISSUE TITLE
setSelection slow on certain device

### ISSUE THREAD

**Issue by elnoxvie** [pakerfeldt/android-viewflow#49]
This happened when i did setSelection to switch to the desired list. It has a delay for about 4 - 7 seconds. On faster device like samsung galaxy s2 it seems to be all right but not on older or less powerful device.

**Comment by pakerfeldt** [comment]
setSelection should be optimized a bit. It re-creates all views in the buffer when called. Larger buffer, more views to populate for your adapter. Is the UI unaccessible during this time?

**Comment by elnoxvie** [comment]
Thanks. I like your implementation on buffer but nowadays, it seems that the device is powerful enough to handle at least 20 pages full of views.. why not just store them inside the memory instead. thus views doesn't need to be created and thus speed up the selection. ViewPager is actually has much faster implementation. I am not sure how its internal mechanism works but it's quite efficient.

**Comment by pakerfeldt** [comment]
That's not the only use case. Consider a use case where you have an unknown number of elements in the adapter. A number that may grow over time as you flow through the view. Also, consider the use case where each view loads a resource over the internet. You typically don't want to load all those resources if not necessary.

**Comment by elnoxvie** [comment]
I see. Thanks for the explanation.
