### ISSUE TITLE
Building a jar won't include res/values/attrs.xml

### ISSUE THREAD

**Issue by likebobby** [pakerfeldt/android-viewflow#50]
The attributes in attrs.xml is not included in the jar built with ant. Referencing the jar file will then miss the attributes when declaring the viewflow in layout xml:s. I don't know if this is possible at all. Wrote a question related to it some time ago http://stackoverflow.com/questions/6428700/android-library-project-as-compiled-jar-library 

Maybe the only way is to move the Android resource files to the referencing project and let it refernence the java code in the jar?

From: http://developer.android.com/guide/developing/projects/index.html#considerations

"You cannot export a library project to a JAR file
A library cannot be distributed as a binary file (such as a jar file). This is because the library project is compiled by the main project to use the correct resource IDs."

**Comment by csgavino** [comment]
Any updates?

**Comment by pakerfeldt** [comment]
If someone points me to a working solution I'll pull it off.

**Comment by meredrica** [comment]
The problem seems to be the A with the circle on top of your name in the copyright.
it gave me a hell lot of trouble. I changed it to a normal A and everything works again

**Comment by orac** [comment]
There's currently no way for Android projects to include XML (or other) resources from JAR files. Either include ViewFlow as an "Android library project", or use the JAR and copy the resources into your project by hand.
