### ISSUE TITLE
Setting font of Titles in TitleFlowIndicator

### ISSUE THREAD

**Issue by SeanPONeil** [pakerfeldt/android-viewflow#51]
Is there a way to use a custom font for the titles in the TitleFlowIndicator?

**Comment by pakerfeldt** [comment]
Not at the moment. Are you talking about custom fonts as in fonts you provide with your application or as those provided by the system?

**Comment by pakerfeldt** [comment]
Nevermind, I implemented both in https://github.com/pakerfeldt/android-viewflow/commit/6befb6b80447774ec8a9dcb90a2b38b02c4919c0

Either use android:typeface (and optionally android:textStyle) or if you provide your own font use app:customTypeface. Set it to the path of your font relative assets, e.g. fonts/Antic.ttf. See viewflow-example.

**Comment by SeanPONeil** [comment]
I was going to do a pull request tonight for this, but this is cool too! Thank you

**Comment by pakerfeldt** [comment]
Did you solve it in a similar fashion?

**Comment by SeanPONeil** [comment]
I had only implemented the android:typeface feature, but it was nearly exactly what you had committed

**Comment by pakerfeldt** [comment]
okay, cool.
