### ISSUE TITLE
why viewFlow.setSelection() doesn't work?

### ISSUE THREAD

**Issue by zhouYunan2010** [pakerfeldt/android-viewflow#53]
when my activity start,I want to the second view to show,not the first default one,
I use  setSelection(2) , but it doesn't work , could you help me?

**Comment by pakerfeldt** [comment]
Use setAdapter(myAdapter, 1); instead.

**Comment by zhouYunan2010** [comment]
but I can't find the method? 
only  public void setAdapter(Adapter adapter) {..}

**Comment by zhouYunan2010** [comment]
pakerfeldt, thank you so much
I download the newest version, and it works well.
