### ISSUE TITLE
Viewflow

### ISSUE THREAD

**Issue by sundarsan** [pakerfeldt/android-viewflow#54]
Is it possible to add multiple listview in a viewflow.....Kindly let me if thats possible ....

**Comment by pakerfeldt** [comment]
If by that you mean that each of the views in the viewflow contains a listview, yes that's possible.

**Comment by sundarsan** [comment]
yes absolutely
I am very much new to android......Kindly give me some sample for have
Listviews in all the view of viewflow as you said.
        Looking for ur reply as sooon as possible

2012/1/5 Patrik kerfeldt <
reply@reply.github.com

**Comment by pakerfeldt** [comment]
Sorry, but I can't give you that kind of support. I simply don't have the time. You should look in the viewflow-examples folder for getting started help.

**Comment by sundarsan** [comment]
I tried with ur sample ....
   Let me tell you what i have done

```
 I added a listview in diff_View2.xml

 and added this
```

ListView listView = (ListView) findViewById(R.id.listView2);

String[] Values = new String[] { "Cupcake", "Donut", "Eclair", "Froyo",

"Gingerbread", "Honeycomb", "IceCream Sandwich"};

listView.setAdapter(new ArrayAdapter<String>(this,

android.R.layout.simple_list_item_1, Values));

Bt whatever i add i am getting listView only in the First View of the
Viewflow

Kindly suggest me where i am doing mistake

2012/1/6 Patrik kerfeldt <
reply@reply.github.com

**Comment by pakerfeldt** [comment]
Just as you have an ArrayAdapter for your listview you need an Adapter for the viewflow. This adapter implements getView(...) and here you need to inflate your listview and populate it with another adapter (like the one you just wrote).

If you get a listview for the first view only, you need to have a look at the adapter implementation and the getView(...) method. For each position you need to return a valid view (a listview in your case).

**Comment by sundarsan** [comment]
Hi,

   I have tried my level best with above code attached....Moreover i tried
debugging as well..
     Bt cant able to find where i did mistake..Kindly help me in this issue

2012/1/6 Patrik kerfeldt <
reply@reply.github.com

**Comment by sundarsan** [comment]
Looking forward to your help in this...I done all things which you said in
the previous reply but still didnt work..

2012/1/9 sundar rajan sundarsym@gmail.com

**Comment by sundarsan** [comment]
Whenever u find time try to provide me some sample with the above req

2012/1/10 sundar rajan sundarsym@gmail.com

**Comment by pakerfeldt** [comment]
What you ask for is simply elementary knowledge of the Android platform. This tutorial might help you: http://www.vogella.de/articles/AndroidListView/article.html

**Comment by sundarsan** [comment]
come on i knew this is elementary ...Just leave it ...Let me show with my
knowledge
what this elementary boy can do in future....

2012/1/25 Patrik kerfeldt <
reply@reply.github.com

**Comment by pakerfeldt** [comment]
I'm sorry to hear that you get upset. But you have to accept the fact that I don't have time to give you the complete example you ask for. Especially when there's already a lot of very god tutorials which, together with the examples in android-viewflow should be enough to understand how to create a viewflow with multiple list views.

**Comment by sundarsan** [comment]
Its k dude....I will try to manage

2012/1/26 Patrik kerfeldt <
reply@reply.github.com

**Comment by gothion** [comment]
Hello , Patrik! 
      I am a beginner in learning  android . and I found one of your work viewflow, which I think very excellent, may contain some bug. According to the log ,I found that when Keep sliding the screen, strings  in the green block  (05-25 10:32:25.370: D/viewflow(2536): Size of mLoadedViews: 5, Size of mRecycledViews: 4, X: 640, Y: 0),   and (05-25 10:32:25.380: D/viewflow(2536): IndexInAdapter: 5, IndexInBuffer: 3  can be get. And then the index out of bounds will occur.which will cause the  appliacation of your example to crash.

May this string ,05-25 10:15:35.590: E/AndroidRuntime(1914):    at org.taptwo.android.widget.ViewFlow.postViewSwitched(ViewFlow.java:667),  be helpful in debugging.
  it would be very helpful for you to fix this,and I will be very happy for your kindness responding
 best regards!
