### ISSUE TITLE
Titles do not display properly with max right value set in SetAdapter

### ISSUE THREAD

**Issue by neofloww** [pakerfeldt/android-viewflow#58]
To reproduce set line 38 in TitleViewFlowExample to
viewFlow.setAdapter(adapter, 6); // to start at the far right view.
Then the tile improperly displays
Cupcake   IceCream Sandwich

**Comment by neofloww** [comment]
I changed the code in TitleFlowIndicator to set the currentposition as follows
    public void setTitleProvider(TitleProvider provider, int position) {
        titleProvider = provider;
        currentPosition = position;
    }
and it fixed this problem.

**Comment by pakerfeldt** [comment]
Thank you.
