### ISSUE TITLE
Add new viewgroup?

### ISSUE THREAD

**Issue by aeroperf** [pakerfeldt/android-viewflow#67]
This may not be the correct forum for this question, but is it possible to add a new view group (a new page) upon a button click at run time? Same with removal of a page. I've been searching the code for something to add/remove view, but did not see anything. The number of view seem to be set up in code. Thanks.

**Comment by pakerfeldt** [comment]
A ViewFlow is always backed up by an Adapter and what you want to do is to simply add/remove items to/from this Adapter.
