### ISSUE TITLE
Errors in viewflow code when added to a project.

### ISSUE THREAD

**Issue by dfetter** [pakerfeldt/android-viewflow#8]
I can import the viewflow project into eclipse perfectly fine, but when I add it as a library to my project I get several errors. Most of them are complaining about @Override lines, and Eclipse suggests I should remove them. Doing so eliminates the errors. However, there is one error that I cannot resolve...

In ViewFlow.java, I am getting an error in the OnConfigurationChanged method. It says that the method is undefined for the class AdapterView<Adapter>.

How can I resolve this?

**Comment by pakerfeldt** [comment]
The @Override issue suggests that you are running an old version of the Java compiler. Make sure you use Java 1.6 by going into project settings and look for Java Compiler. That will probably resolve your second issue as well.

**Comment by dfetter** [comment]
You are right. Changing the compiler to 1.6 fixed the @override problems. The onConfigurationChanged error was due to my target-sdk being 7 in my default.properties. I had to change it to android-8 because onConfigurationChanged wasn't added to View until then.
