### ISSUE TITLE
Increase Size of CircleFlowIndicator 

### ISSUE THREAD

**Issue by Rstar** [pakerfeldt/android-viewflow#86]
Hello , 
            How can i increase size of Circle Flow > is there any method or any static value that can increase circle size

**Comment by orac** [comment]
In your XML layout, set the `radius` attribute, as described in the README. For example:

```
<org.taptwo.android.widget.CircleFlowIndicator
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_height="wrap_content" android:layout_width="wrap_content"
    app:radius="5dp" />
```

Currently this is the only way to increase the radius: there's no mutator function for it in `CircleFlowIndicator`.
