### ISSUE TITLE
setSelection shows wrong view if called before measure

### ISSUE THREAD

**Issue by jspeth** [pakerfeldt/android-viewflow#9]
If you call setSelection() with something other than 0 before the first measure pass has been performed, the ViewFlow will display the wrong view.

For instance, we call setSelection in our activities onCreate to take you to one of the middle items.  The displayed view will be sidebuffer views to the left of the one you expect, for whatever value you have for sidebuffer.

I've been able to get it to work correctly by changing line 165 from:
    scrollTo(mCurrentScreen \* width, 0);
to:
    mScroller.startScroll(0, 0, mCurrentScreen \* width, 0, 0);

But I'm not sure exactly why that works, or why the scrollTo isn't working in the first place.

**Comment by pakerfeldt** [comment]
Are you using the latest version? I'm pretty sure I solved this precise
issue in the latest commit.

On Jun 24, 2011 4:51 PM, "jspeth" <
reply@reply.github.com>
wrote:

**Comment by jspeth** [comment]
Yes, it's the latest version.  Try adding
    viewFlow.setSelection(3);
right after setting the adapter in CircleViewFlowExample.java to see it.  It shows the first view, since sidebuffer is set to 3.  If you change sidebuffer to 1 then it shows view 2.

Thanks, by the way.  This view is really useful.

**Comment by pakerfeldt** [comment]
Okay, Ill look into it. Unfortunately not until sunday. Thanks for the
report.
On Jun 24, 2011 5:18 PM, "jspeth" <
reply@reply.github.com>
wrote:
